# Generated by Django 5.1.2 on 2024-10-18 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_vulnerabilidad', models.CharField(choices=[('Abandono', 'Abandono'), ('Enfermedad', 'Enfermedad'), ('Maltrato', 'Maltrato'), ('Otros', 'Otros')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ayuda', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Adopción', 'Adopción'), ('Hogar de paso', 'Hogar de paso'), ('Medicamentos', 'Medicamentos'), ('Otros', 'Otros')], max_length=50)),
                ('descripcion', models.TextField()),
                ('oferente', models.CharField(max_length=100)),
                ('fecha_ofrecimiento', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas', to='landing.animal')),
            ],
        ),
    ]
